name: Build Debug Apk and Deploy

on:
  pull_request:
    branches:
      - dev

jobs:
  # Debug build and upload apk to artifact
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Generate Debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload APK to artifacts
        uses: actions/upload-artifact@master
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk

  # Download debug apk from artifact and Deploy apk to firebase
  deploy-firebase:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@master
        with:
          name: app-debug.apk

      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: debug-test
          file: app-debug.apk